// This file is generated by update-version.ps1 
 
using System.Reflection;
 
[assembly: AssemblyVersion("ad9dabe2f7daaa706d29cca3aecc7567f806b19a")]
[assembly: AssemblyInformationalVersion("ad9dabe")]
