// This file is generated by update-version.ps1 
 
using System.Reflection;
 
[assembly: AssemblyVersion("84f4eb8a78707375e493e65bb0653b89f1683258")]
[assembly: AssemblyInformationalVersion("84f4eb8")]
