// This file is generated by update-version.ps1 
 
using System.Reflection;
 
[assembly: AssemblyVersion("8aa63fd38f11d8905775289b74abee469985d5cb")]
[assembly: AssemblyInformationalVersion("8aa63fd")]
