$tag = git describe --always --tags "--abbrev=0"
$revision = git describe --always --tags

$text = @"
// This file is generated by update-version.ps1 
 
using System.Reflection;
 
[assembly: AssemblyVersion("$tag")]
[assembly: AssemblyInformationalVersion("$revision")]
"@

$text | Out-File $PSScriptRoot\..\QuickLook.Plugin.JupyterNotebook\GitVersion.cs -Encoding utf8


$xml = [xml](Get-Content $PSScriptRoot\..\QuickLook.Plugin.JupyterNotebook\QuickLook.Plugin.Metadata.Base.config)
$xml.Metadata.Version="$revision"
$xml.Save("$PSScriptRoot\..\QuickLook.Plugin.JupyterNotebook\QuickLook.Plugin.Metadata.config")