param(
	[string] $ProjectDir,
	[string] $SolutionDir,
	[string] $TargetDir)

$ProjectDir = $ProjectDir.Trim()
$SolutionDir = $SolutionDir.Trim()
$TargetDir = $TargetDir.Trim()

$tag = (git describe --always --tags "--abbrev=0").Split("/")[-1]
$revision = (git describe --always --tags).Split("/")[-1]

$text = @"
// This file is generated by update-version.ps1 
 
using System.Reflection;
 
[assembly: AssemblyVersion("$tag")]
[assembly: AssemblyInformationalVersion("$revision")]
"@

$text | Out-File "$ProjectDir\Properties\GitVersion.cs" -Encoding utf8


$xml = [xml](Get-Content $ProjectDir\QuickLook.Plugin.Metadata.Base.config)
$xml.Metadata.Version="$revision"
$xml.Save("$ProjectDir\QuickLook.Plugin.Metadata.config")